import type {
  FoodItem,
  FoodCategory,
  FoodDetailItem,
  AnalysisResult,
  SourceRef,
  PackagingStructure,
  StructureLayer,
  Recommendation,
  Requirement,
  LayerMaterial,
} from './analysis';
import type { CreateAnalysisInput } from '@foodpack/shared';

export const OFFLINE_CATEGORIES: FoodCategory[] = [
  { id: 'cat-1', slug: 'fruits', name: 'Fruits', description: 'Fresh whole fruit commodities.' },
  { id: 'cat-2', slug: 'vegetables', name: 'Vegetables', description: 'Fresh vegetable commodities.' },
  { id: 'cat-3', slug: 'grains-cereals', name: 'Grains & Cereals', description: 'Staple grains and milled cereal products.' },
  { id: 'cat-4', slug: 'pulses', name: 'Pulses', description: 'Dried legumes and lentils.' },
  { id: 'cat-5', slug: 'spices', name: 'Spices', description: 'Dried spice powders and whole spices.' },
  { id: 'cat-6', slug: 'nuts', name: 'Nuts & Seeds', description: 'Tree nuts and oilseeds.' },
  { id: 'cat-7', slug: 'dairy', name: 'Dairy', description: 'Milk and milk-derived products.' },
  { id: 'cat-8', slug: 'processed-bakery', name: 'Processed & Bakery', description: 'Processed and baked snack foods.' },
  { id: 'cat-9', slug: 'beverages', name: 'Beverages', description: 'Tea, coffee, and beverage ingredients.' },
];

const REF_KADER: SourceRef = {
  id: 'ref-kader',
  citation: 'Kader, A.A. (ed.)',
  publication: 'Postharvest Technology of Horticultural Crops (UC ANR 3311)',
  year: 2002,
  url: 'https://postharvest.ucdavis.edu',
};

const REF_USDA: SourceRef = {
  id: 'ref-usda',
  citation: 'USDA Agricultural Research Service',
  publication: 'USDA FoodData Central & Handbook 66',
  year: 2019,
  url: 'https://fdc.nal.usda.gov',
};

const REF_FAO: SourceRef = {
  id: 'ref-fao',
  citation: 'FAO Food Loss & Waste Model',
  publication: 'Global Food Losses and Food Waste',
  year: 2018,
  url: 'https://www.fao.org',
};

const REF_ROBERTSON: SourceRef = {
  id: 'ref-robertson',
  citation: 'Robertson, G.L.',
  publication: 'Food Packaging: Principles and Practice (3rd Edition)',
  year: 2012,
  url: 'https://www.crcpress.com',
};

const REF_SELKE: SourceRef = {
  id: 'ref-selke',
  citation: 'Selke, S.E.M. & Culter, J.D.',
  publication: 'Plastics Packaging: Properties, Processing, Applications, and Regulations (3rd Edition)',
  year: 2016,
  url: 'https://www.hanserpublications.com',
};

const REF_ASTM: SourceRef = {
  id: 'ref-astm',
  citation: 'ASTM International',
  publication: 'Standard Test Methods for Gas and Water Vapor Transmission (ASTM D3985 / F1249)',
  year: 2020,
  url: 'https://www.astm.org',
};

export const OFFLINE_FOODS: FoodDetailItem[] = [
  {
    id: 'food-mango',
    slug: 'mango',
    name: 'Mango',
    commonNames: ['Aam', 'Alphonso', 'Kesar'],
    scientificName: 'Mangifera indica',
    category: OFFLINE_CATEGORIES[0],
    isFreshProduce: true,
    description: 'Climacteric tropical fruit; chilling-sensitive below ~10-13°C. High moisture, active respiration.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 81, maxValue: 85, unit: '%', confidence: 'MEDIUM', source: REF_USDA },
      { propertyType: 'PH', minValue: 3.4, maxValue: 4.8, unit: 'pH', confidence: 'HIGH', source: REF_KADER },
      { propertyType: 'WATER_ACTIVITY', minValue: 0.97, maxValue: 0.99, unit: 'aw', confidence: 'MEDIUM', source: REF_USDA },
      { propertyType: 'RESPIRATION_RATE', minValue: 20, maxValue: 40, unit: 'mL CO₂/kg·hr', confidence: 'HIGH', source: REF_KADER },
      { propertyType: 'FAT_CONTENT', minValue: 0.2, maxValue: 0.5, unit: '%', confidence: 'MEDIUM', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'CHILLED', minTempC: 10, maxTempC: 13, minRH: 85, maxRH: 90, notes: 'Chilling injury occurs below 10°C.', source: REF_KADER },
      { storageType: 'AMBIENT', minTempC: 20, maxTempC: 25, minRH: 85, maxRH: 90, source: REF_KADER },
    ],
    shelfLifeData: [
      { storageType: 'CHILLED', minDays: 14, maxDays: 28, packagingContext: 'MAP (3-5% O₂, 5-8% CO₂) with EVOH barrier pouch', source: REF_KADER },
      { storageType: 'AMBIENT', minDays: 4, maxDays: 7, packagingContext: 'Unpackaged ambient mandi storage', source: REF_KADER },
    ],
    sources: [REF_KADER, REF_USDA],
  },
  {
    id: 'food-tomato',
    slug: 'tomato',
    name: 'Tomato',
    commonNames: ['Tamatar', 'Roma', 'Beefsteak'],
    scientificName: 'Solanum lycopersicum',
    category: OFFLINE_CATEGORIES[1],
    isFreshProduce: true,
    description: 'Climacteric fruit-vegetable; chilling-sensitive below ~10-13°C. High moisture loss risk.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 94, maxValue: 95, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PH', minValue: 4.3, maxValue: 4.9, unit: 'pH', confidence: 'HIGH', source: REF_KADER },
      { propertyType: 'WATER_ACTIVITY', minValue: 0.98, maxValue: 0.99, unit: 'aw', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'RESPIRATION_RATE', minValue: 10, maxValue: 20, unit: 'mL CO₂/kg·hr', confidence: 'HIGH', source: REF_KADER },
    ],
    storageConditions: [
      { storageType: 'CHILLED', minTempC: 10, maxTempC: 13, minRH: 90, maxRH: 95, notes: 'Store above 10°C to prevent chilling pitting.', source: REF_KADER },
      { storageType: 'AMBIENT', minTempC: 20, maxTempC: 25, minRH: 85, maxRH: 90, source: REF_KADER },
    ],
    shelfLifeData: [
      { storageType: 'CHILLED', minDays: 14, maxDays: 21, packagingContext: 'Micro-perforated BOPP anti-fog film', source: REF_KADER },
      { storageType: 'AMBIENT', minDays: 5, maxDays: 10, packagingContext: 'Corrugated vented tray', source: REF_KADER },
    ],
    sources: [REF_KADER, REF_USDA],
  },
  {
    id: 'food-banana',
    slug: 'banana',
    name: 'Banana',
    commonNames: ['Kela', 'Robusta', 'Cavendish'],
    scientificName: 'Musa acuminata',
    category: OFFLINE_CATEGORIES[0],
    isFreshProduce: true,
    description: 'High climacteric respiration peak; extreme chilling sensitivity below 13°C.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 74, maxValue: 76, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PH', minValue: 4.5, maxValue: 5.2, unit: 'pH', confidence: 'MEDIUM', source: REF_KADER },
      { propertyType: 'RESPIRATION_RATE', minValue: 15, maxValue: 30, unit: 'mL CO₂/kg·hr', confidence: 'HIGH', source: REF_KADER },
    ],
    storageConditions: [
      { storageType: 'CHILLED', minTempC: 13, maxTempC: 15, minRH: 90, maxRH: 95, notes: 'Keep at 13-14°C; skin blackens below 12°C.', source: REF_KADER },
    ],
    shelfLifeData: [
      { storageType: 'CHILLED', minDays: 14, maxDays: 28, packagingContext: 'Modified Atmosphere Packaging with ethylene scrubbers', source: REF_KADER },
      { storageType: 'AMBIENT', minDays: 3, maxDays: 6, packagingContext: 'Open ambient crate', source: REF_KADER },
    ],
    sources: [REF_KADER],
  },
  {
    id: 'food-apple',
    slug: 'apple',
    name: 'Apple',
    commonNames: ['Seb', 'Kashmiri Apple', 'Shimla Apple'],
    scientificName: 'Malus domestica',
    category: OFFLINE_CATEGORIES[0],
    isFreshProduce: true,
    description: 'Tolerates near-freezing cold storage. Controlled atmosphere extends shelf-life up to 6 months.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 84, maxValue: 86, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PH', minValue: 3.3, maxValue: 4.0, unit: 'pH', confidence: 'HIGH', source: REF_KADER },
      { propertyType: 'RESPIRATION_RATE', minValue: 5, maxValue: 15, unit: 'mL CO₂/kg·hr', confidence: 'HIGH', source: REF_KADER },
    ],
    storageConditions: [
      { storageType: 'CHILLED', minTempC: 0, maxTempC: 4, minRH: 90, maxRH: 95, source: REF_KADER },
    ],
    shelfLifeData: [
      { storageType: 'CHILLED', minDays: 30, maxDays: 90, packagingContext: 'Perforated LDPE liner in export cartons', source: REF_KADER },
      { storageType: 'AMBIENT', minDays: 7, maxDays: 14, packagingContext: 'Unpackaged retail rack', source: REF_KADER },
    ],
    sources: [REF_KADER, REF_USDA],
  },
  {
    id: 'food-spinach',
    slug: 'spinach',
    name: 'Spinach',
    commonNames: ['Palak'],
    scientificName: 'Spinacia oleracea',
    category: OFFLINE_CATEGORIES[1],
    isFreshProduce: true,
    description: 'Tender leafy green with massive surface area; extremely high transpiration and respiration.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 91, maxValue: 93, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PH', minValue: 5.5, maxValue: 6.8, unit: 'pH', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'RESPIRATION_RATE', minValue: 60, maxValue: 120, unit: 'mL CO₂/kg·hr', confidence: 'HIGH', source: REF_KADER },
    ],
    storageConditions: [
      { storageType: 'CHILLED', minTempC: 0, maxTempC: 2, minRH: 95, maxRH: 98, notes: 'Near 100% RH required to prevent wilting.', source: REF_KADER },
    ],
    shelfLifeData: [
      { storageType: 'CHILLED', minDays: 10, maxDays: 16, packagingContext: 'Anti-fog laser-perforated BOPP flow-wrap', source: REF_KADER },
      { storageType: 'AMBIENT', minDays: 1, maxDays: 2, packagingContext: 'Open ambient basket', source: REF_FAO },
    ],
    sources: [REF_KADER, REF_FAO],
  },
  {
    id: 'food-potato',
    slug: 'potato',
    name: 'Potato',
    commonNames: ['Aloo'],
    scientificName: 'Solanum tuberosum',
    category: OFFLINE_CATEGORIES[1],
    isFreshProduce: true,
    description: 'Underground tuber; dark storage required to prevent greening and solanine synthesis.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 78, maxValue: 82, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PH', minValue: 5.4, maxValue: 6.2, unit: 'pH', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'RESPIRATION_RATE', minValue: 4, maxValue: 8, unit: 'mL CO₂/kg·hr', confidence: 'MEDIUM', source: REF_KADER },
    ],
    storageConditions: [
      { storageType: 'CHILLED', minTempC: 8, maxTempC: 10, minRH: 90, maxRH: 95, notes: 'Cold-induced sweetening occurs below 6°C.', source: REF_KADER },
    ],
    shelfLifeData: [
      { storageType: 'CHILLED', minDays: 90, maxDays: 180, packagingContext: 'Ventilated mesh sack / UV-blocking pouch', source: REF_KADER },
      { storageType: 'AMBIENT', minDays: 20, maxDays: 45, packagingContext: 'Jute bag dry dark room', source: REF_KADER },
    ],
    sources: [REF_KADER, REF_USDA],
  },
  {
    id: 'food-wheat',
    slug: 'wheat',
    name: 'Wheat Grain',
    commonNames: ['Gehun', 'Sharbati Wheat'],
    scientificName: 'Triticum aestivum',
    category: OFFLINE_CATEGORIES[2],
    isFreshProduce: false,
    description: 'Staple cereal grain; moisture gain triggers mold growth and weevil infestation.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 10, maxValue: 12, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'WATER_ACTIVITY', minValue: 0.50, maxValue: 0.65, unit: 'aw', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PROTEIN_CONTENT', minValue: 11, maxValue: 14, unit: '%', confidence: 'HIGH', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'AMBIENT', minTempC: 15, maxTempC: 28, minRH: 40, maxRH: 65, notes: 'Critical moisture ceiling 12.5%.', source: REF_USDA },
    ],
    shelfLifeData: [
      { storageType: 'AMBIENT', minDays: 365, maxDays: 730, packagingContext: 'Hermetic GrainPro multi-barrier liner', source: REF_FAO },
    ],
    sources: [REF_USDA, REF_FAO],
  },
  {
    id: 'food-rice',
    slug: 'rice',
    name: 'Basmati Rice',
    commonNames: ['Chawal', 'Basmati 1121'],
    scientificName: 'Oryza sativa',
    category: OFFLINE_CATEGORIES[2],
    isFreshProduce: false,
    description: 'Aromatic long-grain rice; vulnerable to moisture absorption, rancidity, and aroma loss.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 11, maxValue: 13, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'WATER_ACTIVITY', minValue: 0.55, maxValue: 0.65, unit: 'aw', confidence: 'HIGH', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'AMBIENT', minTempC: 18, maxTempC: 26, minRH: 45, maxRH: 65, source: REF_USDA },
    ],
    shelfLifeData: [
      { storageType: 'AMBIENT', minDays: 365, maxDays: 730, packagingContext: 'PET/Met-PET/Poly vacuum packaging', source: REF_FAO },
    ],
    sources: [REF_USDA],
  },
  {
    id: 'food-milk',
    slug: 'milk',
    name: 'Pasteurized Milk',
    commonNames: ['Doodh'],
    scientificName: 'Bos taurus',
    category: OFFLINE_CATEGORIES[6],
    isFreshProduce: false,
    description: 'High-perishability fluid dairy; light oxidation of riboflavin and microbial spoilage risks.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 87, maxValue: 88, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PH', minValue: 6.6, maxValue: 6.8, unit: 'pH', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'FAT_CONTENT', minValue: 3.5, maxValue: 4.5, unit: '%', confidence: 'HIGH', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'CHILLED', minTempC: 2, maxTempC: 4, minRH: 70, maxRH: 85, notes: 'Maintain unbroken cold chain <4°C.', source: REF_USDA },
    ],
    shelfLifeData: [
      { storageType: 'CHILLED', minDays: 7, maxDays: 14, packagingContext: 'HDPE opaque jug with UV blocker', source: REF_USDA },
    ],
    sources: [REF_USDA],
  },
  {
    id: 'food-paneer',
    slug: 'paneer',
    name: 'Fresh Paneer',
    commonNames: ['Cottage Cheese'],
    scientificName: 'Dairy cheese coagulum',
    category: OFFLINE_CATEGORIES[6],
    isFreshProduce: false,
    description: 'Acid-coagulated non-melting fresh cheese; extreme water activity and yeast/mold susceptibility.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 50, maxValue: 60, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PH', minValue: 5.6, maxValue: 6.2, unit: 'pH', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'WATER_ACTIVITY', minValue: 0.96, maxValue: 0.98, unit: 'aw', confidence: 'HIGH', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'CHILLED', minTempC: 2, maxTempC: 5, minRH: 85, maxRH: 90, source: REF_USDA },
    ],
    shelfLifeData: [
      { storageType: 'CHILLED', minDays: 21, maxDays: 30, packagingContext: 'Vacuum thermoformed PA/PE barrier pouch', source: REF_USDA },
      { storageType: 'AMBIENT', minDays: 1, maxDays: 2, packagingContext: 'Traditional wet wrap', source: REF_FAO },
    ],
    sources: [REF_USDA],
  },
  {
    id: 'food-lentils',
    slug: 'lentils',
    name: 'Red Lentils (Masoor Dal)',
    commonNames: ['Masoor Dal'],
    scientificName: 'Lens culinaris',
    category: OFFLINE_CATEGORIES[3],
    isFreshProduce: false,
    description: 'High-protein split legume; susceptible to ambient humidity uptake and pest ingress.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 10, maxValue: 12, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'PROTEIN_CONTENT', minValue: 24, maxValue: 26, unit: '%', confidence: 'HIGH', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'AMBIENT', minTempC: 15, maxTempC: 28, minRH: 45, maxRH: 65, source: REF_USDA },
    ],
    shelfLifeData: [
      { storageType: 'AMBIENT', minDays: 365, maxDays: 730, packagingContext: 'BOPP/CPP moisture barrier pouch', source: REF_USDA },
    ],
    sources: [REF_USDA],
  },
  {
    id: 'food-cashew',
    slug: 'cashew',
    name: 'Cashew Nuts',
    commonNames: ['Kaju'],
    scientificName: 'Anacardium occidentale',
    category: OFFLINE_CATEGORIES[5],
    isFreshProduce: false,
    description: 'High lipid oilseed; oxygen ingress causes oxidative lipid rancidity and off-flavor synthesis.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 3, maxValue: 5, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'FAT_CONTENT', minValue: 44, maxValue: 48, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'WATER_ACTIVITY', minValue: 0.35, maxValue: 0.45, unit: 'aw', confidence: 'HIGH', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'AMBIENT', minTempC: 15, maxTempC: 25, minRH: 50, maxRH: 65, notes: 'Nitrogen gas flush required to prevent lipid oxidation.', source: REF_USDA },
    ],
    shelfLifeData: [
      { storageType: 'AMBIENT', minDays: 180, maxDays: 365, packagingContext: 'Nitrogen flushed PET/Alu/PE hermetic pouch', source: REF_USDA },
    ],
    sources: [REF_USDA],
  },
  {
    id: 'food-biscuits',
    slug: 'biscuits',
    name: 'Glucose Biscuits',
    commonNames: ['Biscuits', 'Cookies'],
    scientificName: 'Baked cereal confectionery',
    category: OFFLINE_CATEGORIES[7],
    isFreshProduce: false,
    description: 'Crisp baked snack; hygroscopic moisture absorption leads to sogginess and texture failure.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 2, maxValue: 4, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'WATER_ACTIVITY', minValue: 0.20, maxValue: 0.30, unit: 'aw', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'FAT_CONTENT', minValue: 12, maxValue: 16, unit: '%', confidence: 'HIGH', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'AMBIENT', minTempC: 18, maxTempC: 30, minRH: 40, maxRH: 60, source: REF_USDA },
    ],
    shelfLifeData: [
      { storageType: 'AMBIENT', minDays: 180, maxDays: 270, packagingContext: 'BOPP/Met-BOPP heat sealed flow-wrap', source: REF_USDA },
    ],
    sources: [REF_USDA],
  },
  {
    id: 'food-coffee',
    slug: 'coffee',
    name: 'Roasted Coffee Beans',
    commonNames: ['Coffee', 'Arabica', 'Robusta'],
    scientificName: 'Coffea arabica',
    category: OFFLINE_CATEGORIES[8],
    isFreshProduce: false,
    description: 'Aromatic roasted bean; off-gasses CO₂ while highly sensitive to moisture and oxygen.',
    properties: [
      { propertyType: 'MOISTURE_CONTENT', minValue: 1.5, maxValue: 3, unit: '%', confidence: 'HIGH', source: REF_USDA },
      { propertyType: 'FAT_CONTENT', minValue: 12, maxValue: 15, unit: '%', confidence: 'HIGH', source: REF_USDA },
    ],
    storageConditions: [
      { storageType: 'AMBIENT', minTempC: 15, maxTempC: 25, minRH: 40, maxRH: 60, source: REF_USDA },
    ],
    shelfLifeData: [
      { storageType: 'AMBIENT', minDays: 180, maxDays: 365, packagingContext: 'Tri-laminate PET/Alu/PE with one-way degassing valve', source: REF_USDA },
    ],
    sources: [REF_USDA],
  },
];

export const OFFLINE_MATERIALS: LayerMaterial[] = [
  {
    id: 'mat-ldpe',
    slug: 'ldpe',
    name: 'LDPE Film',
    materialType: 'LDPE',
    description: 'Low-density polyethylene film — cost-effective, heat-sealable, high flexibility with moderate moisture barrier.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 110,
    approxCostMax: 145,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-ldpe-1', propertyType: 'OTR', minValue: 7000, maxValue: 8000, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', notes: 'At ~25 µm gauge.', source: REF_SELKE },
      { id: 'p-ldpe-2', propertyType: 'WVTR', minValue: 16, maxValue: 20, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', notes: 'At ~25 µm gauge.', source: REF_SELKE },
      { id: 'p-ldpe-3', propertyType: 'THICKNESS', minValue: 25, maxValue: 75, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-ldpe-4', propertyType: 'TENSILE_STRENGTH', minValue: 10, maxValue: 20, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-ldpe-5', propertyType: 'SEAL_STRENGTH', minValue: 3, maxValue: 5, unit: 'N/15mm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-ldpe-6', propertyType: 'PUNCTURE_RESISTANCE', minValue: 4, maxValue: 7, unit: 'N', confidence: 'LOW', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-hdpe',
    slug: 'hdpe',
    name: 'HDPE Container / Film',
    materialType: 'HDPE',
    description: 'High-density polyethylene — stiffer and superior moisture barrier compared to LDPE. Excellent chemical resistance.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 125,
    approxCostMax: 160,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-hdpe-1', propertyType: 'OTR', minValue: 1800, maxValue: 3000, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-hdpe-2', propertyType: 'WVTR', minValue: 6, maxValue: 10, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-hdpe-3', propertyType: 'THICKNESS', minValue: 25, maxValue: 120, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-hdpe-4', propertyType: 'TENSILE_STRENGTH', minValue: 20, maxValue: 35, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-bopp',
    slug: 'bopp',
    name: 'BOPP Film (Biaxially Oriented PP)',
    materialType: 'PP',
    description: 'Biaxially oriented polypropylene — superb optical clarity, high tensile strength, and low water vapor transmission.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 140,
    approxCostMax: 185,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-bopp-1', propertyType: 'OTR', minValue: 1500, maxValue: 2500, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-bopp-2', propertyType: 'WVTR', minValue: 5, maxValue: 10, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-bopp-3', propertyType: 'THICKNESS', minValue: 15, maxValue: 40, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-bopp-4', propertyType: 'TENSILE_STRENGTH', minValue: 130, maxValue: 180, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-pet-film',
    slug: 'pet-film',
    name: 'PET Film (BoPET)',
    materialType: 'PET',
    description: 'Biaxially oriented PET film — robust oxygen barrier, high mechanical rigidity and thermal dimensional stability.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 160,
    approxCostMax: 210,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-pet-1', propertyType: 'OTR', minValue: 50, maxValue: 100, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', notes: 'At ~12 µm gauge.', source: REF_SELKE },
      { id: 'p-pet-2', propertyType: 'WVTR', minValue: 20, maxValue: 40, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', notes: 'At ~12 µm gauge.', source: REF_SELKE },
      { id: 'p-pet-3', propertyType: 'THICKNESS', minValue: 12, maxValue: 23, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-pet-4', propertyType: 'TENSILE_STRENGTH', minValue: 190, maxValue: 220, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-metallized-pet',
    slug: 'metallized-pet',
    name: 'Metallized PET (Met-PET)',
    materialType: 'METALLIZED_FILM',
    description: 'Vacuum-deposited aluminum layer on BoPET — dramatic gas and light barrier boost for high-fat and light-sensitive goods.',
    recyclable: false,
    monoMaterial: false,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 220,
    approxCostMax: 290,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-mpet-1', propertyType: 'OTR', minValue: 0.8, maxValue: 3.0, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-mpet-2', propertyType: 'WVTR', minValue: 0.5, maxValue: 1.8, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-mpet-3', propertyType: 'THICKNESS', minValue: 12, maxValue: 18, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-mpet-4', propertyType: 'TENSILE_STRENGTH', minValue: 180, maxValue: 210, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-alu-foil',
    slug: 'alu-foil-laminate',
    name: 'Aluminum Foil Barrier Laminate',
    materialType: 'ALU_FOIL_LAMINATE',
    description: 'Multilayer foil laminate (PET/Alu/PE) providing near-absolute hermetic barrier against oxygen, moisture, and UV light.',
    recyclable: false,
    monoMaterial: false,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 320,
    approxCostMax: 420,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-alu-1', propertyType: 'OTR', minValue: 0.01, maxValue: 0.2, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'HIGH', notes: 'Pinhole-free foil is effectively an absolute barrier.', source: REF_SELKE },
      { id: 'p-alu-2', propertyType: 'WVTR', minValue: 0.01, maxValue: 0.2, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'HIGH', notes: 'Complete moisture hermeticity.', source: REF_SELKE },
      { id: 'p-alu-3', propertyType: 'THICKNESS', minValue: 60, maxValue: 90, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-alu-4', propertyType: 'SEAL_STRENGTH', minValue: 35, maxValue: 50, unit: 'N/15mm', confidence: 'HIGH', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-pla-film',
    slug: 'pla-film',
    name: 'PLA Film (Polylactic Acid)',
    materialType: 'BIODEGRADABLE_FILM',
    description: '100% bio-based compostable bioplastic derived from fermented plant starch (corn/sugarcane). Certified EN 13432.',
    recyclable: false,
    monoMaterial: true,
    biodegradable: true,
    bioBased: true,
    approxCostMin: 280,
    approxCostMax: 360,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-pla-1', propertyType: 'OTR', minValue: 150, maxValue: 400, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-pla-2', propertyType: 'WVTR', minValue: 15, maxValue: 35, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-pla-3', propertyType: 'THICKNESS', minValue: 20, maxValue: 40, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-pla-4', propertyType: 'TENSILE_STRENGTH', minValue: 45, maxValue: 70, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-cellulose-film',
    slug: 'cellulose-film',
    name: 'Regenerated Cellulose Film (NatureFlex)',
    materialType: 'BIODEGRADABLE_FILM',
    description: 'Home and industrially compostable transparent film derived from certified sustainable wood pulp with barrier topcoat.',
    recyclable: false,
    monoMaterial: true,
    biodegradable: true,
    bioBased: true,
    approxCostMin: 340,
    approxCostMax: 450,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-cel-1', propertyType: 'OTR', minValue: 80, maxValue: 150, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-cel-2', propertyType: 'WVTR', minValue: 5, maxValue: 20, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-cel-3', propertyType: 'THICKNESS', minValue: 20, maxValue: 35, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-cel-4', propertyType: 'TENSILE_STRENGTH', minValue: 50, maxValue: 85, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-micro-perf',
    slug: 'micro-perforated-bopp',
    name: 'Micro-Perforated BOPP Film',
    materialType: 'MICRO_PERFORATED_FILM',
    description: 'Laser-perforated polypropylene film engineered for active respiration balance and condensation avoidance in fresh produce.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 180,
    approxCostMax: 240,
    costUnit: '₹/kg',
    sources: [REF_ROBERTSON],
    properties: [
      { id: 'p-mp-1', propertyType: 'OTR', minValue: 3000, maxValue: 15000, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', notes: 'Engineered per perforation density for target commodity.', source: REF_ROBERTSON },
      { id: 'p-mp-2', propertyType: 'WVTR', minValue: 30, maxValue: 100, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', source: REF_ROBERTSON },
      { id: 'p-mp-3', propertyType: 'THICKNESS', minValue: 20, maxValue: 40, unit: 'µm', confidence: 'MEDIUM', source: REF_ROBERTSON },
      { id: 'p-mp-4', propertyType: 'TENSILE_STRENGTH', minValue: 120, maxValue: 160, unit: 'MPa', confidence: 'MEDIUM', source: REF_ROBERTSON },
    ],
  },
  {
    id: 'mat-bopa-evoh',
    slug: 'bopa-evoh-lldpe',
    name: 'Multilayer BOPA / EVOH / LLDPE',
    materialType: 'MULTILAYER_FILM',
    description: 'High-performance co-extruded barrier laminate designed for modified atmosphere packaging (MAP) and flex-crack resistance.',
    recyclable: false,
    monoMaterial: false,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 260,
    approxCostMax: 350,
    costUnit: '₹/kg',
    sources: [REF_ASTM, REF_SELKE],
    properties: [
      { id: 'p-bopa-1', propertyType: 'OTR', minValue: 1.5, maxValue: 3.5, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'HIGH', source: REF_ASTM },
      { id: 'p-bopa-2', propertyType: 'WVTR', minValue: 2.5, maxValue: 4.5, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'HIGH', source: REF_ASTM },
      { id: 'p-bopa-3', propertyType: 'THICKNESS', minValue: 65, maxValue: 85, unit: 'µm', confidence: 'HIGH', source: REF_SELKE },
      { id: 'p-bopa-4', propertyType: 'TENSILE_STRENGTH', minValue: 140, maxValue: 190, unit: 'MPa', confidence: 'HIGH', source: REF_SELKE },
      { id: 'p-bopa-5', propertyType: 'PUNCTURE_RESISTANCE', minValue: 24, maxValue: 32, unit: 'N', confidence: 'HIGH', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-rigid-pet',
    slug: 'rigid-pet-tray',
    name: 'Rigid Thermoformed PET Tray',
    materialType: 'PET',
    description: 'Clear thermoformed clamshell or punnet for berries, cherry tomatoes, and cut fruit. High impact protection.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 150,
    approxCostMax: 195,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-rpet-1', propertyType: 'OTR', minValue: 5, maxValue: 15, unit: 'cc/m²·day', testConditionTempC: 23, testConditionRH: 0, confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-rpet-2', propertyType: 'THICKNESS', minValue: 250, maxValue: 350, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-rpet-3', propertyType: 'TENSILE_STRENGTH', minValue: 50, maxValue: 70, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-rpet-4', propertyType: 'PUNCTURE_RESISTANCE', minValue: 8, maxValue: 15, unit: 'N', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-kraft-pe',
    slug: 'kraft-pe-liner',
    name: 'Kraft Paper with PE Liner',
    materialType: 'MONO_MATERIAL',
    description: 'Natural unbleached kraft paper laminated with a thin PE seal layer for granular staples, flour, and pulses.',
    recyclable: true,
    monoMaterial: false,
    biodegradable: false,
    bioBased: true,
    approxCostMin: 90,
    approxCostMax: 130,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-kpe-1', propertyType: 'WVTR', minValue: 15, maxValue: 20, unit: 'g/m²·day', testConditionTempC: 38, testConditionRH: 90, confidence: 'MEDIUM', notes: 'Dominated by PE liner.', source: REF_SELKE },
      { id: 'p-kpe-2', propertyType: 'THICKNESS', minValue: 100, maxValue: 200, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-kpe-3', propertyType: 'TENSILE_STRENGTH', minValue: 15, maxValue: 25, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-woven-pp',
    slug: 'woven-pp-fabric',
    name: 'Woven Polypropylene Sacks',
    materialType: 'WOVEN_PP',
    description: 'Circular woven PP tape fabric — India Mandi standard for 25kg–50kg bulk transport of grains, potatoes, and onions.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: false,
    bioBased: false,
    approxCostMin: 95,
    approxCostMax: 125,
    costUnit: '₹/kg',
    sources: [REF_ROBERTSON],
    properties: [
      { id: 'p-wpp-1', propertyType: 'OTR', minValue: 30000, maxValue: 80000, unit: 'cc/m²·day', confidence: 'LOW', notes: 'Open woven weave — breathable approximation.', source: REF_ROBERTSON },
      { id: 'p-wpp-2', propertyType: 'WVTR', minValue: 3000, maxValue: 8000, unit: 'g/m²·day', confidence: 'LOW', source: REF_ROBERTSON },
      { id: 'p-wpp-3', propertyType: 'THICKNESS', minValue: 200, maxValue: 300, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-wpp-4', propertyType: 'TENSILE_STRENGTH', minValue: 30, maxValue: 45, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-wpp-5', propertyType: 'PUNCTURE_RESISTANCE', minValue: 15, maxValue: 25, unit: 'N', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-jute',
    slug: 'jute-fabric',
    name: 'Natural Jute Sacking',
    materialType: 'JUTE',
    description: '100% natural biodegradable coarse woven jute Hessian fabric for breathable farm-gate bulk handling.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: true,
    bioBased: true,
    approxCostMin: 70,
    approxCostMax: 100,
    costUnit: '₹/kg',
    sources: [REF_ROBERTSON],
    properties: [
      { id: 'p-jute-1', propertyType: 'OTR', minValue: 30000, maxValue: 80000, unit: 'cc/m²·day', confidence: 'LOW', source: REF_ROBERTSON },
      { id: 'p-jute-2', propertyType: 'WVTR', minValue: 3000, maxValue: 8000, unit: 'g/m²·day', confidence: 'LOW', source: REF_ROBERTSON },
      { id: 'p-jute-3', propertyType: 'THICKNESS', minValue: 300, maxValue: 500, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-jute-4', propertyType: 'TENSILE_STRENGTH', minValue: 20, maxValue: 30, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-jute-5', propertyType: 'PUNCTURE_RESISTANCE', minValue: 10, maxValue: 18, unit: 'N', confidence: 'MEDIUM', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-corrugated',
    slug: 'corrugated-fiberboard',
    name: 'Corrugated Master Fiberboard',
    materialType: 'CORRUGATED_FIBERBOARD',
    description: 'Fluted corrugated paperboard box for secondary packaging, cushioning, and export stacking.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: true,
    bioBased: true,
    approxCostMin: 55,
    approxCostMax: 85,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-corr-1', propertyType: 'THICKNESS', minValue: 2500, maxValue: 4000, unit: 'µm', confidence: 'HIGH', source: REF_SELKE },
      { id: 'p-corr-2', propertyType: 'TENSILE_STRENGTH', minValue: 15, maxValue: 30, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-corr-3', propertyType: 'PUNCTURE_RESISTANCE', minValue: 25, maxValue: 45, unit: 'N', confidence: 'HIGH', source: REF_SELKE },
    ],
  },
  {
    id: 'mat-paperboard',
    slug: 'paperboard',
    name: 'Folding Carton Paperboard',
    materialType: 'MONO_MATERIAL',
    description: 'Solid bleached sulfate (SBS) folding paperboard for retail cartons and primary dry-food display packaging.',
    recyclable: true,
    monoMaterial: true,
    biodegradable: true,
    bioBased: true,
    approxCostMin: 75,
    approxCostMax: 110,
    costUnit: '₹/kg',
    sources: [REF_SELKE],
    properties: [
      { id: 'p-pbrd-1', propertyType: 'THICKNESS', minValue: 300, maxValue: 600, unit: 'µm', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-pbrd-2', propertyType: 'TENSILE_STRENGTH', minValue: 20, maxValue: 35, unit: 'MPa', confidence: 'MEDIUM', source: REF_SELKE },
      { id: 'p-pbrd-3', propertyType: 'PUNCTURE_RESISTANCE', minValue: 5, maxValue: 10, unit: 'N', confidence: 'LOW', source: REF_SELKE },
    ],
  },
];

export const STRUCTURE_MANGO_EVOH: PackagingStructure = {
  id: 'struct-mango-evoh',
  name: 'Multilayer BOPA / EVOH / LLDPE High-Barrier Pouch',
  slug: 'bopa-evoh-lldpe',
  description: 'Co-extruded multilayer high-barrier film designed for modified atmosphere packaging (MAP) of climacteric fruits.',
  structureType: 'MULTILAYER_FILM',
  supportsMap: true,
  layers: [
    {
      id: 'l-01',
      order: 1,
      layerRole: 'OUTER',
      thicknessMinMicron: 15,
      thicknessMaxMicron: 15,
      material: {
        id: 'mat-bopa-15',
        name: 'Biaxially Oriented Polyamide (BOPA)',
        slug: 'bopa-15',
        materialType: 'POLYAMIDE',
        properties: [
          { id: 'p-1', propertyType: 'TENSILE_STRENGTH', value: 240, unit: 'MPa' },
          { id: 'p-2', propertyType: 'PUNCTURE_RESISTANCE', value: 22, unit: 'N' },
        ],
      },
    },
    {
      id: 'l-02',
      order: 2,
      layerRole: 'BARRIER',
      thicknessMinMicron: 12,
      thicknessMaxMicron: 15,
      material: {
        id: 'mat-evoh-15',
        name: 'Ethylene Vinyl Alcohol Copolymer (EVOH 32 mol%)',
        slug: 'evoh-32',
        materialType: 'BARRIER_COPOLYMER',
        properties: [
          { id: 'p-3', propertyType: 'OTR', value: 1.5, unit: 'cc/m²·day·atm' },
          { id: 'p-4', propertyType: 'WVTR', value: 18.0, unit: 'g/m²·day' },
        ],
      },
    },
    {
      id: 'l-03',
      order: 3,
      layerRole: 'SEAL',
      thicknessMinMicron: 50,
      thicknessMaxMicron: 60,
      material: {
        id: 'mat-m-lldpe-50',
        name: 'Metallocene LLDPE Food-Contact Sealant',
        slug: 'm-lldpe-50',
        materialType: 'POLYOLEFIN',
        properties: [
          { id: 'p-5', propertyType: 'SEAL_STRENGTH', value: 34, unit: 'N/15mm' },
          { id: 'p-6', propertyType: 'WVTR', value: 4.2, unit: 'g/m²·day' },
        ],
      },
    },
  ],
};

export const STRUCTURE_TOMATO_AF: PackagingStructure = {
  id: 'struct-tomato-af',
  name: 'Micro-Perforated BOPP Anti-Fog Punnet Film',
  slug: 'bopp-anti-fog-microperf',
  description: 'Breathable mono-material polypropylene film engineered with non-migratory anti-fog coating and calibrated laser micro-perforations.',
  structureType: 'MONOMATERIAL_FILM',
  supportsMap: true,
  layers: [
    {
      id: 'l-t01',
      order: 1,
      layerRole: 'OUTER',
      thicknessMinMicron: 20,
      thicknessMaxMicron: 25,
      material: {
        id: 'mat-bopp-af-25',
        name: 'Anti-Fog Treated Oriented Polypropylene',
        slug: 'bopp-af-25',
        materialType: 'ORIENTED_POLYOLEFIN',
        properties: [
          { id: 'pt-1', propertyType: 'TENSILE_STRENGTH', value: 175, unit: 'MPa' },
          { id: 'pt-2', propertyType: 'PUNCTURE_RESISTANCE', value: 16, unit: 'N' },
        ],
      },
    },
    {
      id: 'l-t02',
      order: 2,
      layerRole: 'BARRIER',
      thicknessMinMicron: 10,
      thicknessMaxMicron: 15,
      material: {
        id: 'mat-perf-core',
        name: 'Laser-Perforated Permeation Control Core',
        slug: 'laser-perf-core',
        materialType: 'PERMEABLE_MEMBRANE',
        properties: [
          { id: 'pt-3', propertyType: 'OTR', value: 920, unit: 'cc/m²·day·atm' },
          { id: 'pt-4', propertyType: 'WVTR', value: 7.5, unit: 'g/m²·day' },
        ],
      },
    },
    {
      id: 'l-t03',
      order: 3,
      layerRole: 'SEAL',
      thicknessMinMicron: 35,
      thicknessMaxMicron: 40,
      material: {
        id: 'mat-cpp-seal',
        name: 'Cast Polypropylene (CPP) Heat Sealant',
        slug: 'cpp-seal',
        materialType: 'POLYOLEFIN',
        properties: [
          { id: 'pt-5', propertyType: 'SEAL_STRENGTH', value: 26, unit: 'N/15mm' },
          { id: 'pt-6', propertyType: 'WVTR', value: 6.8, unit: 'g/m²·day' },
        ],
      },
    },
  ],
};

export const STRUCTURE_RICE_MET: PackagingStructure = {
  id: 'struct-rice-met',
  name: 'Heavy-Duty Metallized PET / LLDPE Triplex Laminate',
  slug: 'met-pet-lldpe-triplex',
  description: 'Ultra-high barrier laminate providing maximum moisture protection and aroma preservation for export-grade grains.',
  structureType: 'METALLIZED_LAMINATE',
  supportsMap: false,
  layers: [
    {
      id: 'l-r01',
      order: 1,
      layerRole: 'OUTER',
      thicknessMinMicron: 12,
      thicknessMaxMicron: 12,
      material: {
        id: 'mat-bopet-12',
        name: 'Printable Biaxially Oriented PET',
        slug: 'bopet-12',
        materialType: 'POLYESTER',
        properties: [
          { id: 'pr-1', propertyType: 'TENSILE_STRENGTH', value: 230, unit: 'MPa' },
          { id: 'pr-2', propertyType: 'PUNCTURE_RESISTANCE', value: 20, unit: 'N' },
        ],
      },
    },
    {
      id: 'l-r02',
      order: 2,
      layerRole: 'BARRIER',
      thicknessMinMicron: 12,
      thicknessMaxMicron: 15,
      material: {
        id: 'mat-met-pet-12',
        name: 'Vacuum Metallized PET (Alu Vapor Deposition)',
        slug: 'met-pet-12',
        materialType: 'METALLIZED_BARRIER',
        properties: [
          { id: 'pr-3', propertyType: 'OTR', value: 0.7, unit: 'cc/m²·day·atm' },
          { id: 'pr-4', propertyType: 'WVTR', value: 0.35, unit: 'g/m²·day' },
        ],
      },
    },
    {
      id: 'l-r03',
      order: 3,
      layerRole: 'SEAL',
      thicknessMinMicron: 75,
      thicknessMaxMicron: 85,
      material: {
        id: 'mat-lldpe-heavy',
        name: 'Heavy Duty Slip-Modified LLDPE Liner',
        slug: 'lldpe-heavy',
        materialType: 'POLYOLEFIN',
        properties: [
          { id: 'pr-5', propertyType: 'SEAL_STRENGTH', value: 42, unit: 'N/15mm' },
          { id: 'pr-6', propertyType: 'WVTR', value: 3.1, unit: 'g/m²·day' },
          { id: 'pr-7', propertyType: 'PUNCTURE_RESISTANCE', value: 28, unit: 'N' },
        ],
      },
    },
  ],
};

export const OFFLINE_ANALYSES: AnalysisResult[] = [
  {
    id: 'ana-demo-01',
    status: 'COMPLETED',
    food: OFFLINE_FOODS[0], // Mango
    productState: 'FRESH_WHOLE',
    storageType: 'CHILLED',
    transportType: 'EXPORT_SEA',
    targetShelfLifeDays: 28,
    packageWeightKg: 2.5,
    objective: 'BALANCED',
    requirement: {
      targetOtrMin: 1.0,
      targetOtrMax: 3.0,
      targetWvtrMin: 3.0,
      targetWvtrMax: 6.0,
      mapRecommended: true,
      recommendedO2Min: 3.0,
      recommendedO2Max: 5.0,
      recommendedCo2Min: 5.0,
      recommendedCo2Max: 8.0,
      limitingFactors: ['Respiration gas accumulation', 'Anthracnose fungal spoilage', 'Chilling injury below 10°C'],
      dataConfidence: 'HIGH',
    },
    recommendations: [
      {
        id: 'rec-01',
        rank: 1,
        isRecommended: true,
        overallScore: 94,
        scoreBreakdown: {
          barrierSuitability: 98,
          moistureProtection: 90,
          mechanicalSuitability: 92,
          sealability: 95,
          shelfLifePotential: 94,
          cost: 88,
          sustainability: 82,
          mapSuitability: 96,
        },
        estimatedShelfLifeMinDays: 24,
        estimatedShelfLifeMaxDays: 28,
        shelfLifeConfidence: 'HIGH',
        estimatedCostMin: 18.5,
        estimatedCostMax: 22.0,
        costUnit: 'INR/pack',
        sustainabilityNotes: 'EVOH core with bio-based PE skin provides recycling stream compatibility.',
        explanation: [
          'High barrier to O₂ and moisture retains 3% O₂ and 6% CO₂ active modified atmosphere.',
          'Delayed climacteric ripening and respiration suppresses anthracnose mold development.',
          'Hermetic seal integrity withstands 21-day maritime reefer container transit.'
        ],
        aiExplanation: 'The multilayer BOPA/EVOH/LLDPE structure offers the optimal gas permeability balance required for chilled mango transport, delivering 26 days of fresh shelf life.',
        structure: STRUCTURE_MANGO_EVOH,
        material: STRUCTURE_MANGO_EVOH.layers[0]?.material,
      },
      {
        id: 'rec-01-alt',
        rank: 2,
        isRecommended: false,
        overallScore: 88,
        scoreBreakdown: {
          barrierSuitability: 86,
          moistureProtection: 88,
          mechanicalSuitability: 90,
          sealability: 92,
          shelfLifePotential: 86,
          cost: 94,
          sustainability: 90,
          mapSuitability: 84,
        },
        estimatedShelfLifeMinDays: 18,
        estimatedShelfLifeMaxDays: 22,
        shelfLifeConfidence: 'MEDIUM',
        estimatedCostMin: 14.0,
        estimatedCostMax: 16.5,
        costUnit: 'INR/pack',
        sustainabilityNotes: 'Recyclable mono-PE pouch with barrier coating.',
        explanation: [
          'Cost-effective alternative for domestic express road freight.',
          'Offers standard barrier protection with 100% PE recycling stream compatibility.'
        ],
        aiExplanation: 'A secondary candidate suitable for regional refrigerated transit with shorter transit duration.',
        structure: STRUCTURE_TOMATO_AF,
        material: STRUCTURE_TOMATO_AF.layers[0]?.material,
      },
    ],
    createdAt: new Date(Date.now() - 3600000 * 4).toISOString(),
    updatedAt: new Date(Date.now() - 3600000 * 4).toISOString(),
  },
  {
    id: 'ana-demo-02',
    status: 'COMPLETED',
    food: OFFLINE_FOODS[1], // Tomato
    productState: 'FRESH_WHOLE',
    storageType: 'CHILLED',
    transportType: 'REGIONAL',
    targetShelfLifeDays: 21,
    packageWeightKg: 1.0,
    objective: 'MAX_SHELF_LIFE',
    requirement: {
      targetOtrMin: 800,
      targetOtrMax: 1200,
      targetWvtrMin: 6.0,
      targetWvtrMax: 9.0,
      mapRecommended: true,
      recommendedO2Min: 4.0,
      recommendedO2Max: 8.0,
      recommendedCo2Min: 2.0,
      recommendedCo2Max: 5.0,
      limitingFactors: ['Moisture condensation droplet fogging', 'Anaerobic fermentation risk', 'Pitting below 10°C'],
      dataConfidence: 'HIGH',
    },
    recommendations: [
      {
        id: 'rec-02',
        rank: 1,
        isRecommended: true,
        overallScore: 91,
        scoreBreakdown: {
          barrierSuitability: 89,
          moistureProtection: 92,
          mechanicalSuitability: 90,
          sealability: 92,
          shelfLifePotential: 92,
          cost: 95,
          sustainability: 92,
          mapSuitability: 90,
        },
        estimatedShelfLifeMinDays: 18,
        estimatedShelfLifeMaxDays: 22,
        shelfLifeConfidence: 'HIGH',
        estimatedCostMin: 6.2,
        estimatedCostMax: 8.5,
        costUnit: 'INR/pack',
        sustainabilityNotes: 'Monomaterial BOPP is 100% recyclable in mechanical polyolefin streams.',
        explanation: [
          'Anti-fog surfactant layer eliminates condensation droplet fogging inside punnets.',
          'Laser micro-perforations maintain aerobic respiration and avoid anaerobic fermentation.',
        ],
        aiExplanation: 'Laser-perforated BOPP prevents dew-point moisture condensation while allowing physiological gas exchange for table tomatoes.',
        structure: STRUCTURE_TOMATO_AF,
        material: STRUCTURE_TOMATO_AF.layers[0]?.material,
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 2).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'ana-demo-03',
    status: 'COMPLETED',
    food: OFFLINE_FOODS[7], // Basmati Rice
    productState: 'PROCESSED_DRY',
    storageType: 'AMBIENT',
    transportType: 'NATIONAL',
    targetShelfLifeDays: 365,
    packageWeightKg: 5.0,
    objective: 'MIN_COST',
    requirement: {
      targetOtrMin: 0.1,
      targetOtrMax: 1.0,
      targetWvtrMin: 0.1,
      targetWvtrMax: 0.5,
      mapRecommended: false,
      limitingFactors: ['Water vapor uptake causing caking and softening', 'Lipid and aroma oxidation'],
      dataConfidence: 'HIGH',
    },
    recommendations: [
      {
        id: 'rec-03',
        rank: 1,
        isRecommended: true,
        overallScore: 96,
        scoreBreakdown: {
          barrierSuitability: 99,
          moistureProtection: 99,
          mechanicalSuitability: 95,
          sealability: 98,
          shelfLifePotential: 96,
          cost: 92,
          sustainability: 78,
          mapSuitability: 80,
        },
        estimatedShelfLifeMinDays: 365,
        estimatedShelfLifeMaxDays: 540,
        shelfLifeConfidence: 'HIGH',
        estimatedCostMin: 24.0,
        estimatedCostMax: 28.5,
        costUnit: 'INR/pack',
        sustainabilityNotes: 'Ultra-durable laminate reduces food loss and grain wastage to <0.1%.',
        explanation: [
          'Near-zero water vapor transmission prevents ambient humidity uptake and grain softening.',
          'Metallized barrier blocks light oxidation and preserves volatile aromatic compounds.',
        ],
        aiExplanation: 'The high-barrier metallized laminate delivers exceptional moisture and aroma protection for long-term grain storage up to 18 months.',
        structure: STRUCTURE_RICE_MET,
        material: STRUCTURE_RICE_MET.layers[0]?.material,
      },
    ],
    createdAt: new Date(Date.now() - 86400000 * 5).toISOString(),
    updatedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
];

export function createOfflineAnalysis(input: CreateAnalysisInput): AnalysisResult {
  const food = OFFLINE_FOODS.find((f) => f.id === input.foodId || f.slug === input.foodId) ?? OFFLINE_FOODS[0];
  const isFresh = food.isFreshProduce;
  const isGrainOrDry = food.category.slug === 'grains-cereals' || food.category.slug === 'pulses' || food.category.slug === 'nuts';

  let structure: PackagingStructure;
  let expl: string[];
  let aiExpl: string;
  let oScore: number;
  let scores: Record<string, number>;

  if (isFresh) {
    structure = STRUCTURE_MANGO_EVOH;
    expl = [
      `Maintains controlled headspace gas equilibrium to suppress ${food.name.toLowerCase()} respiration.`,
      `Prevents internal dew-point condensation and microbial fungal decay during ${input.transportType.toLowerCase()} transit.`,
      `Optimal hermetic heat seal integrity retains protective barrier atmosphere for target duration.`,
    ];
    aiExpl = `Based on validated physiological respiration kinetics (${food.name}), this EVOH barrier structure prevents aerobic decay and enzymatic browning, reaching ${Math.round(input.targetShelfLifeDays * 1.15)} days of fresh shelf life.`;
  } else if (isGrainOrDry) {
    structure = STRUCTURE_RICE_MET;
    expl = [
      'Near-zero water vapor transmission rate (WVTR < 0.5 g/m²·day) stops ambient moisture uptake.',
      'Metallized barrier reflects light and prevents lipid/flavor oxidation.',
      'High puncture and drop resistance withstands transport logistics.',
    ];
    aiExpl = `The metallized triplex barrier completely blocks atmospheric humidity and lipid auto-oxidation, ensuring ${food.name.toLowerCase()} remains fresh and pest-free for up to ${Math.round(input.targetShelfLifeDays * 1.25)} days.`;
  } else {
    structure = STRUCTURE_TOMATO_AF;
    expl = [
      'Active anti-fog coating prevents water droplet fogging and mold formation.',
      'Laser micro-perforations maintain oxygen ingress to prevent anaerobic hypoxia.',
      '100% recyclable monomaterial polyolefin structure.',
    ];
    aiExpl = `Calibrated oxygen permeability maintains equilibrium modified atmosphere without anaerobic spoilage, providing reliable protection for ${food.name.toLowerCase()}.`;
  }

  // Objective-based scoring
  if (input.objective === 'MAX_SHELF_LIFE') {
    oScore = 95;
    scores = { barrierSuitability: 98, moistureProtection: 96, mechanicalSuitability: 94, sealability: 96, shelfLifePotential: 96, cost: 84, sustainability: 80, mapSuitability: 95 };
  } else if (input.objective === 'MIN_COST') {
    oScore = 93;
    scores = { barrierSuitability: 88, moistureProtection: 90, mechanicalSuitability: 88, sealability: 92, shelfLifePotential: 88, cost: 98, sustainability: 84, mapSuitability: 88 };
  } else if (input.objective === 'SUSTAINABILITY') {
    oScore = 94;
    scores = { barrierSuitability: 90, moistureProtection: 90, mechanicalSuitability: 90, sealability: 92, shelfLifePotential: 90, cost: 88, sustainability: 98, mapSuitability: 90 };
  } else {
    oScore = 94;
    scores = { barrierSuitability: 95, moistureProtection: 94, mechanicalSuitability: 92, sealability: 95, shelfLifePotential: 94, cost: 90, sustainability: 86, mapSuitability: 94 };
  }

  const minDays = Math.max(3, Math.round(input.targetShelfLifeDays * 0.95));
  const maxDays = Math.round(input.targetShelfLifeDays * 1.35);
  const costBase = 12.0 * Math.max(1, Math.log10(input.packageWeightKg + 1));

  const newAnalysis: AnalysisResult = {
    id: `ana-${Date.now()}`,
    status: 'COMPLETED',
    food,
    productState: input.productState,
    storageType: input.storageType,
    transportType: input.transportType,
    targetShelfLifeDays: input.targetShelfLifeDays,
    packageWeightKg: input.packageWeightKg,
    objective: input.objective,
    requirement: {
      targetOtrMin: 1.0,
      targetOtrMax: 3.5,
      targetWvtrMin: 0.5,
      targetWvtrMax: 4.0,
      mapRecommended: isFresh,
      recommendedO2Min: 3.0,
      recommendedO2Max: 5.0,
      recommendedCo2Min: 4.0,
      recommendedCo2Max: 8.0,
      limitingFactors: isFresh ? ['Chilling sensitivity', 'Respiration gas accumulation', 'Moisture condensation'] : ['Ambient humidity ingress', 'Lipid oxidation'],
      dataConfidence: 'HIGH',
    },
    recommendations: [
      {
        id: `rec-${Date.now()}-1`,
        rank: 1,
        isRecommended: true,
        overallScore: oScore,
        scoreBreakdown: scores,
        estimatedShelfLifeMinDays: minDays,
        estimatedShelfLifeMaxDays: maxDays,
        shelfLifeConfidence: 'HIGH',
        estimatedCostMin: Number((costBase * 0.85).toFixed(1)),
        estimatedCostMax: Number((costBase * 1.2).toFixed(1)),
        costUnit: 'INR/pack',
        sustainabilityNotes: 'Polyolefin and bio-based skin layers compatible with mechanical recycling.',
        explanation: expl,
        aiExplanation: aiExpl,
        structure,
        material: structure.layers[0]?.material,
      },
      {
        id: `rec-${Date.now()}-2`,
        rank: 2,
        isRecommended: false,
        overallScore: oScore - 6,
        scoreBreakdown: { ...scores, cost: scores.cost ? scores.cost - 8 : 80 },
        estimatedShelfLifeMinDays: Math.round(minDays * 0.85),
        estimatedShelfLifeMaxDays: Math.round(maxDays * 0.9),
        shelfLifeConfidence: 'MEDIUM',
        estimatedCostMin: Number((costBase * 0.7).toFixed(1)),
        estimatedCostMax: Number((costBase * 0.95).toFixed(1)),
        costUnit: 'INR/pack',
        sustainabilityNotes: 'Standard laminate alternative with higher recyclability yield.',
        explanation: [
          'Alternative lower-cost packaging structure for short-distance distribution.',
          'Provides standard barrier protection suitable for rapid turnover channels.',
        ],
        aiExplanation: 'A secondary cost-effective candidate suitable for domestic regional supply chains with faster inventory turnaround.',
        structure: STRUCTURE_TOMATO_AF,
        material: STRUCTURE_TOMATO_AF.layers[0]?.material,
      },
    ],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };

  OFFLINE_ANALYSES.unshift(newAnalysis);
  return newAnalysis;
}
